### PR TITLE
Dropped the window and breakpoints services from utilities. We decide…

### PR DESCRIPTION
**Pull request by KorinaGraber**
…d to keep these in app core for now. The window service in this project wasn't working properly for some reason, and I think we decided it was too view specific anyway.

### CODE REVIEW

**Comment by KorinaGraber** [comment]
Version bumped from https://github.com/RenovoSolutions/TypeScript-Angular-Utilities/pull/10 (0.6.6)

**Comment by SonofNun15** [comment]
What order should we merge #10, #12, and #13 in?

**Comment by SonofNun15** [comment]
Version keeps increasing. Version order is 10, 12, 13 consecutively.

**Comment by KorinaGraber** [comment]
Yes

**Pull request merged**
