### PR TITLE
Export barrels

### PR DESCRIPTION
**Pull request by KorinaGraber**
Initial idea for resolving https://renovo.myjetbrains.com/youtrack/issue/RLv21-37

Creates a folder that reflects the 'source' hierarchy at the root of the project for importing into other projects
Consumers can simply do:
`import {} from 'typescript-angular-utilities/services/array';`
And get any array types they want

The one thing that is a little interesting about this is that it means we now have two `services` folders. One within the source folder and one at the root. An alternative would be to put a file for each service barrel at the root of the project, but that would clutter things up a little bit.

Or, we could create another folder for `output` or `exports` or `dist` or something to that effect, put the barrels in there, and add a build task to copy the main.ts over to there. Then we can configure systemjs to point to that folder when you ask for typescript-angular-utilities.

### CODE REVIEW

**Comment by KorinaGraber** [comment]
Note, I started with array because it was the first service in alphabetical order, not because it was the most important. :smirk:

**Comment by JamieBowen** [comment]
What if the `typescript-angular-utilities/services/array` folder had an `exports` file that acts as a barrel for all of the array services, and the root folder also had an `exports` file of its own that aggregates all of the various export files from each sub-directory?

**Comment by KorinaGraber** [comment]
Are you suggesting that every type in `typescript-angular-utilities` be accessible via direct import from a single file? That seems a little interesting. It seems like it might be a lot of noise when you're trying to figure out what types to get. For example, if there was an interface type that was related to a specific service, you would have no idea, because intellisense would pick up every interface in the project.

**Comment by JamieBowen** [comment]
True, the noise could be borderline deafening, but isn't that how Angular 2 does it?  You can import anything in `angular2/core` straight from core, right?  You don't have to drill down any deeper than the root.  Maybe I'm wrong about that though.  I'm not super-familiar with it yet.

**Comment by JamieBowen** [comment]
If it's that noisy, is that a sign that `typescript-angular-utilities` is too big?

**Comment by KorinaGraber** [comment]
Angular sort of works that way, but only because it's already broken up into many projects `core`, `common`, `http`, `forms`, etc. Plus they actually still do have you drill down further for somethings, such as `@angular/core/testing`. 

Could be. I could see splitting it into several smaller packages if we felt it was worth the effort. That might make it more desirable for other angular 2 developers looking for open source packages.

**Comment by KorinaGraber** [comment]
The data contracts piece could probably be a library all on its own. Then we could have a typescript utility library with array, object, string, number, time, date, etc, and maybe one for some more angular specific stuff.

**Comment by JoshDSommer** [comment]
I agree it would be very nice to have access to all the available classes interfaces right from the get go. However maybe some of the larger complex items could be drilled into instead. like angulars testing.

**Comment by KorinaGraber** [comment]
Possible alternative proposal: split the typescript-angular-utilities repository into several smaller repositories. These will be open-sourced so there is no worry of them costing Renovo extra expense. Once these repositories are manageable sizes, we can export most types on the root import, with possible nested imports if necessary. In particular, we might keep the test tools in a `/testing` import since this is explicitly used for testing.

The main hurtle in this approach will be managing the additional npm repositories, and perhaps more so, our build server runs against this repo. However, these will hopefully have to change infrequently.

**Pull request closed without merging**
