### PR TITLE
Add typical karma configurations to utilities

### PR DESCRIPTION
**Pull request by SonofNun15**

### CODE REVIEW

**Comment by SonofNun15** [comment]
@SamGraber, it's possible we could do something similar with shared gulp tasks. This was the purpose of gulp-utilities before, but it's going to kind of die after webpack...

**Comment by KorinaGraber** [comment]
:shipit:

**Comment by KorinaGraber** [comment]
So essentially we would do the same thing as here where the gulp tasks live in the tests folder, while outside consumers would specify their own gulpfile to use the tasks?

**Comment by KorinaGraber** [comment]
Similar to how you were doing gulp-utilities

**Comment by SonofNun15** [comment]
Right. Maybe not the test folder, since not strictly test related. Perhaps a gulp service folder?

**Comment by KorinaGraber** [comment]
Sure. Is it safe to assume that all consumers will have a ./source folder that needs to be cleaned?

**Comment by KorinaGraber** [comment]
Or do we want to do `target` like you did in gulp-utilities, so they can do clean.source or whatever

**Comment by SonofNun15** [comment]
Sure, we could make it more flexible then... Perhaps an option for naming the task and specifying the folder. This task would have to be opt-in, like gulp utilities. Ideally with two levels. First option is to call an exported utility function that does the work. Second option is to call a .config(gulp) function that wires up the task on gulp.

**Pull request merged**
