### PR TITLE
Updating out of sync utilities. Adding time utility

### PR DESCRIPTION
**Pull request by dannyrb**
todo: 
- Additional tests for number utility's `integerDivide`
- Port genericSearchFilter (and IFilter from components)

### CODE REVIEW

**Comment by SonofNun15** [comment]
Based on the "todo" I'm assuming that the tests for `integerDivide` are going to be in a separate PR, correct?

**Comment by SonofNun15** [comment]
Looks good, nice work!

**Comment by dannyrb** [comment]
Your assumption about `integerDivide` coming in a separate PR is correct. I wanted to finish porting existing code before I add my own.

**Comment by SonofNun15** [comment]
Good call.

**Comment by SonofNun15** [comment]
That def makes it easier to review as well.

**Pull request merged**
